# Generated by Django 6.0.1 on 2026-04-26 06:08

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='blog_catego_slug_fc0bb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/', verbose_name='تصویر')),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice/%Y/%m/', verbose_name='ویس مقاله')),
                ('read_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت زمان مطالعه (دقیقه)')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], db_index=True, default='draft', max_length=10, verbose_name='وضعیت انتشار')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='آدرس')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='دسته بندی')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2, 'نام باید حداقل ۲ کاراکتر باشد.'), django.core.validators.RegexValidator(message='نام فقط می\u200cتواند شامل حروف و فاصله باشد.', regex='^[a-zA-Z\\s\\u0600-\\u06FF\\u0750-\\u077F]+$')], verbose_name='نام')),
                ('body', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(5, 'نظر باید حداقل ۵ کاراکتر باشد.'), django.core.validators.RegexValidator(message='نظر شامل کاراکترهای غیرمجاز است.', regex='^[a-zA-Z0-9\\s\\u0600-\\u06FF\\u0750-\\u077F.,!?()؟؛،\\-]+$')], verbose_name='متن نظر')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='فعال')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2, 'نام باید حداقل ۲ کاراکتر باشد.'), django.core.validators.RegexValidator(message='نام فقط می\u200cتواند شامل حروف و فاصله باشد.', regex='^[a-zA-Z\\s\\u0600-\\u06FF\\u0750-\\u077F]+$')], verbose_name='نام')),
                ('body', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(5, 'نظر باید حداقل ۵ کاراکتر باشد.'), django.core.validators.RegexValidator(message='نظر شامل کاراکترهای غیرمجاز است.', regex='^[a-zA-Z0-9\\s\\u0600-\\u06FF\\u0750-\\u077F.,!?()؟؛،\\-]+$')], verbose_name='متن نظر')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='فعال')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='کامنت')),
            ],
            options={
                'verbose_name': 'پاسخ کامنت',
                'verbose_name_plural': 'پاسخ کامنت ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.SlugField(unique=True, verbose_name='کد کوتاه')),
                ('original_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'لینک کوتاه',
                'verbose_name_plural': 'لینک کوتاه ها',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='blog_commen_created_79f39f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'active', '-created'], name='blog_commen_post_id_9cf0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='replycomment',
            index=models.Index(fields=['-created'], name='blog_replyc_created_c52b10_idx'),
        ),
        migrations.AddIndex(
            model_name='replycomment',
            index=models.Index(fields=['comment', 'active'], name='blog_replyc_comment_5f8978_idx'),
        ),
    ]
