# Generated by Django 6.0.1 on 2026-05-17 15:49

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='برای مرتب\u200cسازی سوالات. عدد کوچکتر بالاتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('post', models.ForeignKey(blank=True, help_text='اگر این سوال مربوط به پست خاصی است، آن را انتخاب کنید. در غیر این صورت خالی بگذارید تا به عنوان سوال عمومی در نظر گرفته شود.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog.post', verbose_name='پست مربوطه')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order', '-created'],
                'indexes': [models.Index(fields=['active', 'order'], name='blog_faq_active_ff1339_idx'), models.Index(fields=['post', 'active'], name='blog_faq_post_id_545012_idx')],
            },
        ),
    ]
