# Generated by Django 6.0.1 on 2026-04-26 06:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoldAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان محصول')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='کد محصول')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='تصویر')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='وزن (گرم)')),
                ('buy_price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت خرید (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_assets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دارایی طلای کاربر',
                'verbose_name_plural': 'دارایی\u200cهای طلای کاربران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_user_status'), models.Index(fields=['status', '-created_at'], name='idx_status_created')],
            },
        ),
    ]
