# Generated by Django 6.0.1 on 2026-05-11 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coineshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoldasset',
            name='code',
        ),
        migrations.AddField(
            model_name='usergoldasset',
            name='gold_price_buy',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت روز طلا خریداری شده)'),
            preserve_default=False,
        ),
    ]
