# Generated by Django 6.0.1 on 2026-04-26 06:09

import django.core.validators
import django.utils.timezone
import django_jalali.db.models
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='فقط ایمیل\u200cهای Gmail معتبر هستند.', regex='^[a-zA-Z0-9][a-zA-Z0-9._]*[a-zA-Z0-9]@gmail\\.com$')], verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='GoldPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='داده\u200cهای فرمت\u200cشده')),
                ('raw_data', models.JSONField(default=dict, verbose_name='داده\u200cهای خام (عددی)')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'کش قیمت طلا',
                'verbose_name_plural': 'کش قیمت\u200cهای طلا',
            },
        ),
        migrations.CreateModel(
            name='ParsianCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سکه')),
                ('weight_gram', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='وزن (گرم)')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='پیشنهادی')),
                ('is_in_stock', models.BooleanField(db_index=True, default=True, verbose_name='موجود در انبار')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سکه پارسیان',
                'verbose_name_plural': 'سکه\u200cهای پارسیان',
                'ordering': ['display_order', 'weight_gram'],
            },
        ),
        migrations.CreateModel(
            name='GoldDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='تاریخ')),
                ('gold_price_irr', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='انس جهانی طلا')),
                ('gold_18k_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='طلای ۱۸ عیار')),
                ('sikka_imami', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سکه امامی')),
                ('sikka_tamam', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سکه تمام بهار آزادی')),
                ('sikka_rub', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='ربع سکه')),
                ('sikka_nim', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='نیم سکه')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دریافت داده')),
            ],
            options={
                'verbose_name': 'قیمت روزانه طلا',
                'verbose_name_plural': 'قیمت\u200cهای روزانه طلا',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date', 'gold_18k_price'], name='idx_date_18k')],
            },
        ),
        migrations.CreateModel(
            name='MarketPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('sell_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت بازار',
                'verbose_name_plural': 'تاریخچه قیمت\u200cهای بازار',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserLandingCoine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, message='نام باید حداقل ۵ کاراکتر باشد')], verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='شماره موبایل نامعتبر است. مثال: 09123456789', regex='^(?:\\+98|0|0098)?9\\d{9}$')], verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, default='', validators=[django.core.validators.MinLengthValidator(10, message='آدرس خیلی کوتاه است (حداقل ۱۰ کاراکتر)')], verbose_name='آدرس')),
                ('post_code', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_postcode', message='کد پستی باید دقیقاً ۱۰ رقم باشد و با ۰ شروع نشود.', regex='^[1-9]\\d{9}$')], verbose_name='کد پستی')),
                ('birthday', django_jalali.db.models.jDateField(blank=True, null=True, validators=[home.models.validate_not_future_jdate], verbose_name='تاریخ تولد')),
                ('create_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('is_call', models.BooleanField(db_index=True, default=False, verbose_name='تماس گرفته شد؟')),
            ],
            options={
                'verbose_name': 'درخواست کاربر',
                'verbose_name_plural': 'درخواست\u200cهای کاربران',
                'ordering': ['-create_date'],
                'indexes': [models.Index(fields=['is_call', '-create_date'], name='idx_call_created')],
            },
        ),
    ]
