"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qcot7m!6cx-glge0!ldczi&zbu2(vg0q2h-+2$0cac&f+7)a65'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['goldestone.ir' , 'www.goldestone.ir']

# Application definition

INSTALLED_APPS = [
    "account", # Coustome Account
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.sitemaps', # Sitemap
    'django.contrib.redirects',
    
    # Third Party App
    'mysql.connector.django',
    'rest_framework',
    'ckeditor',
    'taggit',
    'corsheaders',
    "django_jalali",
    "debug_toolbar",
    
    # Coustome User
    "home",
    "coineshop",
    "blog",
]

JALALI_SETTINGS = {
    # JavaScript static files for the admin Jalali date widget
    "ADMIN_JS_STATIC_FILES": [
        "admin/jquery.ui.datepicker.jalali/scripts/jquery-1.10.2.min.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js",
        "admin/jquery.ui.datepicker.jalali/scripts/calendar.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js",
        "admin/main.js",
    ],
    # CSS static files for the admin Jalali date widget
    "ADMIN_CSS_STATIC_FILES": {
        "all": [
            "admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css",
            "admin/css/main.css",
        ]
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.WWWRedirectMiddleware', # Add WWWRedirectMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Add this Cors Middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware', # Redirect 301
    "debug_toolbar.middleware.DebugToolbarMiddleware",

]

ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.gold_prices', # Custom Template For Show Price Chart
                'home.context_processors.email_form', # Custom Template For Get Email In Footer
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'yhvwlzia_AR_aidaBD',
        'USER': 'yhvwlzia_AR_Aida_gold',
        'PASSWORD': r'\Ql|6J@Tu.n"GfU[',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            'autocommit': True,
        },
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'bot_database.sqlite3',
#     }
# }

SITE_ID = 2

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =========================
# Authentication
# =========================
AUTH_USER_MODEL = "account.CustomUserModel"

AUTHENTICATION_BACKENDS = [
    "account.authentication.PhoneNumberBackend",
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "assets",]
STATIC_ROOT = os.path.join(BASE_DIR, '../public_html/static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '../public_html/media')

# Login and Logout
LOGIN_REDIRECT_URL = "accounts:login"
LOGOUT_REDIRECT_URL = "home:index"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = False
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'harif.academy@gmail.com'
EMAIL_HOST_PASSWORD = 'ngjjdxjrofeblbim'

# CORS Settings
CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOWED_ORIGINS = [
#     'https://baha24.com',
# ]

CORS_ALLOW_METHODS = [
    'GET',
]

CORS_ALLOW_HEADERS = [
    'accept',
]


INTERNAL_IPS = [
    "127.0.0.1",
]



# CKEditor Settings
CKEDITOR_UPLOAD_PATH = 'uploads/CKEditor'
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_CODESNIPPET = "/static/ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"
CKEDITOR_CONFIGS = {
    'default':
        {
            # 'contentsCss': [
            #     '{% static "css/site.css" %}',  # مسیر فایل CSS  که فونت‌ها رو تعریف کردید
            # ],
            'toolbar': 'full',
            'width': 'auto',
            'extraPlugins': ','.join([
                'codesnippet',
                'html5video',
                'pastefromgdocs',
                
            ]),
        },
}



N8N_SECRET_TOKEN = "super-secret-token-for-n8n"


# =========================
# Account Security Settings
# =========================
ACCOUNT_LOCKOUT_MINUTES = 5
ACCOUNT_MAX_FAILED_ATTEMPTS = 5
OTP_EXPIRY_SECONDS = 90
OTP_MAX_ATTEMPTS = 3
OTP_RESEND_COOLDOWN = 60

# =========================
# Session Security
# =========================
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True  # فقط در HTTPS
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week
SECURE_SSL_REDIRECT = True
SECURE_HSTS_PRELOAD = True

# =========================
# CSRF Security
# =========================
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True  # فقط در HTTPS
CSRF_COOKIE_SAMESITE = "strict"

# =========================
# Security Headers
# =========================
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# =========================
# Password Validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 8}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

